image: alpine:3.5

before_script:
  - apk update && apk add openssl
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19_Linux-64bit.tar.gz
  - tar xf hugo_0.19_Linux-64bit.tar.gz --strip-components=1 && mv hugo_0.19_linux_amd64 hugo && cp ./hugo /usr/bin
  - hugo version

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
